version: '3'
networks:
  infra_chatbot:
    external: true

services:
  codeserver:
    image: code_server_cust
    build: ./
    command: sh -c "sysctl fs.inotify.max_user_watches=524288 && sysctl -p"
    deploy:
        resources:
            limits:
              memory: 2048M
    container_name: kwsnet-codeserver-1
    networks:
      - infra_chatbot
    restart: always
    user: root
    volumes:
      - ./vscode/config:/config
    environment:
      VIRTUAL_HOST: kws1.gapmoe.net
      VIRTUAL_PORT: 8443
  codeserver2:
    image: code_server_cust
    build: ./
    command: sh -c "sysctl fs.inotify.max_user_watches=524288 && sysctl -p"
    env_file:
      - ./.env
    deploy:
        resources:
            limits:
              memory: 2048M
    container_name: kwsnet-codeserver-2
    networks:
      - infra_chatbot
    restart: always
    user: root
    volumes:
      - ./vscode2/config:/config
    environment:
      VIRTUAL_HOST: kws1.gapmoe.net
      VIRTUAL_PORT: 8444
